# These are supported funding model platforms

github: vovagorodok
patreon: vovagorodok
ko_fi: vovagorodok
liberapay: vovagorodok
buy_me_a_coffee: vovagorodok
custom: [revolut.me/vovagorodok, paypal.me/vovagorodok]
